import type { Role } from "./roles";

/**
 * Fine-grained permissions, deliberately decoupled from Role (see
 * docs/architecture/07-roles-permissions-matrix.md §7.4) so a future configurable-role
 * system can remap role -> permission without touching call sites like
 * `guard.check(Permission.FARM_CREATE)`.
 *
 * Only the permissions needed for MVP Milestone 0 (companies/users/farms) are defined here;
 * grow this list module by module as each module ships.
 */
export enum Permission {
  COMPANY_READ = "company:read",
  COMPANY_UPDATE = "company:update",

  USER_INVITE = "user:invite",
  USER_READ = "user:read",
  USER_UPDATE_ROLE = "user:update_role",
  USER_REVOKE = "user:revoke",

  FARM_CREATE = "farm:create",
  FARM_READ = "farm:read",
  FARM_UPDATE = "farm:update",
  FARM_DELETE = "farm:delete",

  TANK_CREATE = "tank:create",
  TANK_READ = "tank:read",
  TANK_UPDATE = "tank:update",
  TANK_DELETE = "tank:delete",

  FISH_SPECIES_CREATE = "fish_species:create",
  FISH_SPECIES_READ = "fish_species:read",

  FISH_BATCH_CREATE = "fish_batch:create",
  FISH_BATCH_READ = "fish_batch:read",

  BATCH_MOVEMENT_CREATE = "batch_movement:create",
  BATCH_MOVEMENT_READ = "batch_movement:read",

  FEED_PRODUCT_CREATE = "feed_product:create",
  FEED_PRODUCT_READ = "feed_product:read",

  WAREHOUSE_CREATE = "warehouse:create",
  WAREHOUSE_READ = "warehouse:read",

  FEED_INVENTORY_CREATE = "feed_inventory:create",
  FEED_INVENTORY_READ = "feed_inventory:read",

  FEEDING_EVENT_CREATE = "feeding_event:create",
  FEEDING_EVENT_READ = "feeding_event:read",

  MORTALITY_EVENT_CREATE = "mortality_event:create",
  MORTALITY_EVENT_READ = "mortality_event:read",

  WEIGHT_SAMPLE_CREATE = "weight_sample:create",
  WEIGHT_SAMPLE_READ = "weight_sample:read",

  BIOMASS_SNAPSHOT_CREATE = "biomass_snapshot:create",
  BIOMASS_SNAPSHOT_READ = "biomass_snapshot:read",

  WATER_QUALITY_READING_CREATE = "water_quality_reading:create",
  WATER_QUALITY_READING_READ = "water_quality_reading:read",

  ALERT_READ = "alert:read",
  ALERT_RESOLVE = "alert:resolve",

  AUDIT_LOG_READ = "audit_log:read",

  PLATFORM_ADMIN_CROSS_TENANT_ACCESS = "platform_admin:cross_tenant_access",
}

/**
 * Static role -> permission map. See docs/architecture/07-roles-permissions-matrix.md §7.3
 * for the full target matrix (grows as modules beyond Milestone 0 ship). Phase 2+ replaces
 * this static map with a DB-backed RolePermission table behind the same PermissionsGuard
 * call signature (§7.4) — call sites never need to change.
 */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  PLATFORM_ADMIN: Object.values(Permission),
  COMPANY_OWNER: [
    Permission.COMPANY_READ,
    Permission.COMPANY_UPDATE,
    Permission.USER_INVITE,
    Permission.USER_READ,
    Permission.USER_UPDATE_ROLE,
    Permission.USER_REVOKE,
    Permission.FARM_CREATE,
    Permission.FARM_READ,
    Permission.FARM_UPDATE,
    Permission.FARM_DELETE,
    Permission.TANK_CREATE,
    Permission.TANK_READ,
    Permission.TANK_UPDATE,
    Permission.TANK_DELETE,
    Permission.FISH_SPECIES_CREATE,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_CREATE,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_CREATE,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_CREATE,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_CREATE,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_CREATE,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_CREATE,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_CREATE,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_CREATE,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_CREATE,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_CREATE,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
    Permission.ALERT_RESOLVE,
    Permission.AUDIT_LOG_READ,
  ],
  GENERAL_MANAGER: [
    Permission.COMPANY_READ,
    Permission.USER_INVITE,
    Permission.USER_READ,
    Permission.USER_UPDATE_ROLE,
    Permission.FARM_CREATE,
    Permission.FARM_READ,
    Permission.FARM_UPDATE,
    Permission.FARM_DELETE,
    Permission.TANK_CREATE,
    Permission.TANK_READ,
    Permission.TANK_UPDATE,
    Permission.TANK_DELETE,
    Permission.FISH_SPECIES_CREATE,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_CREATE,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_CREATE,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_CREATE,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_CREATE,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_CREATE,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_CREATE,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_CREATE,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_CREATE,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_CREATE,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_CREATE,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
    Permission.ALERT_RESOLVE,
    Permission.AUDIT_LOG_READ,
  ],
  FARM_MANAGER: [
    Permission.COMPANY_READ,
    Permission.USER_READ,
    Permission.FARM_READ,
    Permission.FARM_UPDATE,
    Permission.TANK_CREATE,
    Permission.TANK_READ,
    Permission.TANK_UPDATE,
    Permission.FISH_SPECIES_CREATE,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_CREATE,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_CREATE,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_CREATE,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_CREATE,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_CREATE,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_CREATE,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_CREATE,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_CREATE,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_CREATE,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_CREATE,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
    Permission.ALERT_RESOLVE,
    Permission.AUDIT_LOG_READ,
  ],
  VETERINARIAN: [
    Permission.COMPANY_READ,
    Permission.FARM_READ,
    Permission.TANK_READ,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_SPECIES_CREATE,
    Permission.FISH_BATCH_READ,
    Permission.FISH_BATCH_CREATE,
    Permission.BATCH_MOVEMENT_READ,
    Permission.BATCH_MOVEMENT_CREATE,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_CREATE,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_CREATE,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_CREATE,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_CREATE,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
    Permission.ALERT_RESOLVE,
  ],
  FEED_MANAGER: [
    Permission.COMPANY_READ,
    Permission.FARM_READ,
    Permission.TANK_READ,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_CREATE,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_CREATE,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_CREATE,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_CREATE,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
  ],
  ACCOUNTANT: [
    Permission.COMPANY_READ,
    Permission.FARM_READ,
    Permission.TANK_READ,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
    Permission.AUDIT_LOG_READ,
  ],
  WORKER: [
    Permission.FARM_READ,
    Permission.TANK_READ,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_CREATE,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_CREATE,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_CREATE,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
  ],
  READ_ONLY: [
    Permission.COMPANY_READ,
    Permission.FARM_READ,
    Permission.TANK_READ,
    Permission.FISH_SPECIES_READ,
    Permission.FISH_BATCH_READ,
    Permission.BATCH_MOVEMENT_READ,
    Permission.FEED_PRODUCT_READ,
    Permission.WAREHOUSE_READ,
    Permission.FEED_INVENTORY_READ,
    Permission.FEEDING_EVENT_READ,
    Permission.MORTALITY_EVENT_READ,
    Permission.WEIGHT_SAMPLE_READ,
    Permission.BIOMASS_SNAPSHOT_READ,
    Permission.WATER_QUALITY_READING_READ,
    Permission.ALERT_READ,
  ],
};
